In [1]:
import numpy as np
import pandas as pd


### numpy array collection

In [3]:
l1=[1,2,3,4,5,6,7,8,9]
ar=np.array(l1)
ar

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
np.array([1,2,3,4,5,6,7,8,9])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
ar.shape

(9,)

In [7]:
### user utility function
print(len(ar))
print(max(ar))
print(min(ar))

9
9
1


In [8]:
np.size(ar)

9

In [10]:
###creating two dimisional array
ar=np.array([[1,2,3],[4,5,6],[7,8,9]])
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
ar.shape

(3, 3)

In [13]:
np.size(ar) ### calculate the total elements in matrix

9

In [15]:
len(ar) ### calculate the no of rows

3

In [17]:
### it will will create single dimision array starting from 1 and upto 11 with space of 0.5
np.arange(1,11,0.5)


array([ 1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,  5.5,  6. ,
        6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. , 10.5])

In [18]:
np.arange(1,11,0.5).shape

(20,)

In [19]:
np.size(np.arange(1,11,0.5))

20

In [20]:
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [21]:
np.linspace(1,10,20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [41]:
##create the random matrix of 10 rows and 5 column with natural number
np.random.rand(10,5)

array([[0.29335085, 0.68611881, 0.71232236, 0.34167877, 0.08328044],
       [0.25543327, 0.8697267 , 0.93149126, 0.85783542, 0.36265942],
       [0.41459305, 0.66803469, 0.80114824, 0.60723101, 0.06971391],
       [0.79787511, 0.25092102, 0.99817789, 0.79117467, 0.94347769],
       [0.51046872, 0.59059283, 0.14769001, 0.32486794, 0.54651272],
       [0.91145474, 0.01880395, 0.92009141, 0.92124844, 0.03669713],
       [0.65435398, 0.70225098, 0.22309734, 0.88838622, 0.7026682 ],
       [0.04422969, 0.55542343, 0.15976443, 0.9469713 , 0.91218667],
       [0.19630523, 0.80727435, 0.59953951, 0.43198346, 0.76544731],
       [0.94072898, 0.98969036, 0.05643181, 0.37028392, 0.81492856]])

In [42]:
###create the random matrix of 10 rows and 5 column with integer
np.random.randn(10,5)

array([[ 0.28761029,  0.27552603, -0.49316194,  1.05678866,  0.28611084],
       [-1.16970935, -1.47957764, -0.53179074,  1.37100798, -0.36546039],
       [ 1.62625631, -0.37426573,  1.22337895,  0.61928178, -1.39060201],
       [-0.86838179,  0.80972701,  0.76809476, -0.70639489,  0.68213812],
       [-1.327455  , -0.6267204 ,  0.18451198,  0.06245887,  0.35672527],
       [-0.63670348,  1.41439941, -1.81070417,  0.32327882, -0.14944903],
       [ 1.10287874,  0.15412127,  0.6086541 , -0.98211091, -1.54909878],
       [-1.54368893, -1.02228333, -1.11140521,  0.83029141,  1.35686322],
       [-0.53775726, -1.11775325,  1.67329626,  1.04551586, -0.2181516 ],
       [ 0.97422051,  1.25304536, -1.88885589,  1.06003588, -1.98375465]])

In [46]:
np.random.randint(1,2,size=(5,5)) ### create matrix with 5 rows and 5 column with range from 1 upto 2

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [50]:
np.random.randint(1,2,50)#### create matrix of 1*1 of range from 1 to 2 and 50 element

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1])

In [51]:
### creating matrix with zeros element
np.zeros([5,5],dtype='int32')

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [52]:
###
np.zeros([5,5],dtype='float32')

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float32)

In [53]:
np.eye(5,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [55]:
###creating matrix with diagonal element one
np.diag(np.eye(5,5))

array([1., 1., 1., 1., 1.])

In [57]:
np.round(np.random.rand(5,5),2)

array([[0.82, 0.33, 0.91, 0.08, 0.87],
       [0.3 , 0.54, 0.51, 0.68, 0.26],
       [0.03, 0.97, 0.78, 0.83, 0.27],
       [0.99, 0.49, 0.18, 0.15, 0.23],
       [0.23, 0.27, 0.44, 0.64, 0.08]])

In [75]:
x=np.round(np.random.rand(5,5),2)

In [76]:
x

array([[0.07, 0.09, 0.6 , 0.74, 0.62],
       [0.92, 0.25, 0.31, 0.73, 0.46],
       [0.49, 0.79, 0.26, 0.07, 0.06],
       [0.88, 0.25, 0.04, 0.75, 0.1 ],
       [0.03, 0.62, 0.25, 0.78, 0.97]])

In [77]:
x[0,0]

0.07

In [78]:
x[0,4]

0.62

In [79]:
x[4,0]

0.03

In [80]:
x[4,4]

0.97

In [81]:
x

array([[0.07, 0.09, 0.6 , 0.74, 0.62],
       [0.92, 0.25, 0.31, 0.73, 0.46],
       [0.49, 0.79, 0.26, 0.07, 0.06],
       [0.88, 0.25, 0.04, 0.75, 0.1 ],
       [0.03, 0.62, 0.25, 0.78, 0.97]])

In [82]:
x[0,0:]

array([0.07, 0.09, 0.6 , 0.74, 0.62])

In [83]:
x[1,0:]

array([0.92, 0.25, 0.31, 0.73, 0.46])

In [85]:
x[2,0:]

array([0.49, 0.79, 0.26, 0.07, 0.06])

In [86]:
x[3,0:]

array([0.88, 0.25, 0.04, 0.75, 0.1 ])

In [89]:
x[4,0:]

array([0.03, 0.62, 0.25, 0.78, 0.97])

In [90]:
x[0:2,0:2]

array([[0.07, 0.09],
       [0.92, 0.25]])

In [91]:
x

array([[0.07, 0.09, 0.6 , 0.74, 0.62],
       [0.92, 0.25, 0.31, 0.73, 0.46],
       [0.49, 0.79, 0.26, 0.07, 0.06],
       [0.88, 0.25, 0.04, 0.75, 0.1 ],
       [0.03, 0.62, 0.25, 0.78, 0.97]])

In [97]:
x[[2,3],1:3]

array([[0.79, 0.26],
       [0.25, 0.04]])

In [100]:
x.reshape(1,-1)

array([[0.07, 0.09, 0.6 , 0.74, 0.62, 0.92, 0.25, 0.31, 0.73, 0.46, 0.49,
        0.79, 0.26, 0.07, 0.06, 0.88, 0.25, 0.04, 0.75, 0.1 , 0.03, 0.62,
        0.25, 0.78, 0.97]])

### numpy operation

In [108]:
a=np.random.randint(1,5,size=(5,5))

In [109]:
b=np.random.randint(5,10,size=(5,5))

In [110]:
a

array([[3, 1, 1, 1, 2],
       [3, 3, 1, 3, 4],
       [1, 3, 2, 2, 2],
       [3, 3, 2, 2, 4],
       [3, 3, 3, 4, 4]])

In [111]:
b

array([[5, 9, 7, 9, 5],
       [6, 5, 5, 6, 7],
       [8, 5, 7, 8, 8],
       [5, 8, 9, 7, 5],
       [9, 9, 9, 5, 6]])

In [112]:
np.add(a,b)

array([[ 8, 10,  8, 10,  7],
       [ 9,  8,  6,  9, 11],
       [ 9,  8,  9, 10, 10],
       [ 8, 11, 11,  9,  9],
       [12, 12, 12,  9, 10]])

In [113]:
np.multiply(a,b)

array([[15,  9,  7,  9, 10],
       [18, 15,  5, 18, 28],
       [ 8, 15, 14, 16, 16],
       [15, 24, 18, 14, 20],
       [27, 27, 27, 20, 24]])

In [114]:
a/b

array([[0.6       , 0.11111111, 0.14285714, 0.11111111, 0.4       ],
       [0.5       , 0.6       , 0.2       , 0.5       , 0.57142857],
       [0.125     , 0.6       , 0.28571429, 0.25      , 0.25      ],
       [0.6       , 0.375     , 0.22222222, 0.28571429, 0.8       ],
       [0.33333333, 0.33333333, 0.33333333, 0.8       , 0.66666667]])

In [117]:
np.squeeze(a)

array([[3, 1, 1, 1, 2],
       [3, 3, 1, 3, 4],
       [1, 3, 2, 2, 2],
       [3, 3, 2, 2, 4],
       [3, 3, 3, 4, 4]])

In [119]:
np.concatenate([a,b])

array([[3, 1, 1, 1, 2],
       [3, 3, 1, 3, 4],
       [1, 3, 2, 2, 2],
       [3, 3, 2, 2, 4],
       [3, 3, 3, 4, 4],
       [5, 9, 7, 9, 5],
       [6, 5, 5, 6, 7],
       [8, 5, 7, 8, 8],
       [5, 8, 9, 7, 5],
       [9, 9, 9, 5, 6]])

In [120]:
np.vstack([a,b])

array([[3, 1, 1, 1, 2],
       [3, 3, 1, 3, 4],
       [1, 3, 2, 2, 2],
       [3, 3, 2, 2, 4],
       [3, 3, 3, 4, 4],
       [5, 9, 7, 9, 5],
       [6, 5, 5, 6, 7],
       [8, 5, 7, 8, 8],
       [5, 8, 9, 7, 5],
       [9, 9, 9, 5, 6]])

In [122]:
np.hstack([a,b])

array([[3, 1, 1, 1, 2, 5, 9, 7, 9, 5],
       [3, 3, 1, 3, 4, 6, 5, 5, 6, 7],
       [1, 3, 2, 2, 2, 8, 5, 7, 8, 8],
       [3, 3, 2, 2, 4, 5, 8, 9, 7, 5],
       [3, 3, 3, 4, 4, 9, 9, 9, 5, 6]])

In [123]:
np.where(a<2)

(array([0, 0, 0, 1, 2], dtype=int64), array([1, 2, 3, 2, 0], dtype=int64))

In [ ]:
np.w